### ISSUE TITLE
URL Encoding Function v2 based on your own algorithm

### ISSUE THREAD

**Issue by koberoi** [xseano/Linkify#1]
Good start using the hash function.  Now, create your own encode algorithm.

Check out how the pros do it: (for functional understanding / requirements)

https://blog.rebrandly.com/the-6-best-url-shorteners-and-how-to-choose-the-right-one-for-you/

Then, implement your algorithm.

Think about cloud scale - 10M URLs, etc.

**Comment by xseano** [comment]
Bijective Algorithm @ PR https://github.com/xseano/Linkify/pull/2
